"""Canonical ε-machine examples from the computational mechanics literature."""

from pensive.examples.epsilon_machines import (
    alternating_biased_coins,
    bernoulli,
    butterfly_process,
    ellison_fig9_forward,
    ellison_fig9_reverse,
    ellison_fig15_bidirectional,
    even_process,
    fair_coin,
    golden_mean,
    golden_mean_bidirectional,
    golden_mean_forward,
    golden_mean_markov,
    golden_mean_reverse,
    golden_mean_shift_parry,
    nemo_process,
    restricted_golden_mean,
    tent_map_misiurewicz_a,
    tent_map_misiurewicz_bidirectional,
    tent_map_misiurewicz_forward,
    tent_map_misiurewicz_hmm,
    tent_map_misiurewicz_information_expected,
    tent_map_misiurewicz_reverse,
)

__all__ = [
    "alternating_biased_coins",
    "bernoulli",
    "butterfly_process",
    "ellison_fig9_forward",
    "ellison_fig9_reverse",
    "ellison_fig15_bidirectional",
    "even_process",
    "fair_coin",
    "golden_mean",
    "golden_mean_forward",
    "golden_mean_markov",
    "golden_mean_reverse",
    "golden_mean_bidirectional",
    "golden_mean_shift_parry",
    "nemo_process",
    "restricted_golden_mean",
    "tent_map_misiurewicz_a",
    "tent_map_misiurewicz_bidirectional",
    "tent_map_misiurewicz_forward",
    "tent_map_misiurewicz_hmm",
    "tent_map_misiurewicz_information_expected",
    "tent_map_misiurewicz_reverse",
]
