"""Finite automata and transducers."""

# ``atomaton`` is an intentional pun on atomic automaton.
from sofic.automata.algorithms import (
    MinimizationAlgorithm,
    complete,
    determinize,
    equivalent,
    minimize,
    trim,
)
from sofic.automata.base import LabeledAutomaton
from sofic.automata.buchi import BuchiAutomaton
from sofic.automata.canonical.atomaton import Atomaton, AtomicAutomaton, MaximizedPrimeAtomaton
from sofic.automata.canonical.rfsa import CanonicalRFSA, ResidualFiniteStateAutomaton
from sofic.automata.dfa import DFA
from sofic.automata.enumeration.icdfa import (
    ICDFAString,
    count_icdfa,
    count_icdfa_empty,
    dfa_to_icdfa_string,
    first_icdfa_empty_string,
    icdfa_count_flag_sequences,
    icdfa_flags_from_string,
    icdfa_next_flags,
    icdfa_string_from_flags,
    icdfa_string_to_dfa,
    iter_icdfa,
    iter_icdfa_empty_strings,
    last_icdfa_empty_string,
    next_icdfa_empty_string,
    validate_icdfa_empty_string,
)
from sofic.automata.enumeration.idfa import (
    MISSING_TRANSITION,
    count_accessible_idfa,
    first_idfa_string,
    iter_idfa_strings,
    rank_idfa_string,
    reroot_idfa_string,
    unrank_idfa_string,
    validate_idfa_string,
)
from sofic.automata.languages import AutomatonLanguage, RegularLanguage
from sofic.automata.learning.active import (
    AutomatonEquivalenceOracle,
    EquivalenceOracle,
    ExhaustiveEquivalenceOracle,
    FunctionMealyOracle,
    FunctionMembershipOracle,
    LanguageMembershipOracle,
    MealyEquivalenceOracle,
    MealyExhaustiveEquivalenceOracle,
    MealyMembershipOracle,
    MembershipOracle,
    RandomWalkEquivalenceOracle,
    TransducerOutputOracle,
    learn_dfa_from_language,
    learn_dfa_lstar,
    learn_dfa_ttt,
    learn_mealy_from_transducer,
    learn_mealy_lstar,
)
from sofic.automata.learning.alergia import learn_pfa_alergia
from sofic.automata.learning.dfasat import learn_dfa_sat
from sofic.automata.learning.edsm import learn_dfa_edsm
from sofic.automata.learning.nlstar import learn_prime_atomaton_nlstar, learn_rfsa_from_language, learn_rfsa_nlstar
from sofic.automata.learning.observation import ObservationTable
from sofic.automata.learning.papni import (
    DyckAlphabet,
    encode_dyck_samples,
    encode_dyck_word,
    is_well_matched,
    learn_sofic_dyck_shift_papni,
    sofic_dyck_shift_from_papni_dfa,
)
from sofic.automata.learning.rpni import learn_dfa_rpni
from sofic.automata.nfa import NFA
from sofic.automata.nwa import NestedWord, NestedWordAutomaton
from sofic.automata.regex import automaton_to_regex
from sofic.automata.subsequential import (
    SubsequentialTransducer,
    WeightedFiniteStateTransducer,
)
from sofic.automata.transducer_operations import (
    ERROR_STATE,
    ERROR_SYMBOL,
    compose_transducer_generator,
    compose_transducers,
    generator_product,
    transduce_generator,
    transducer_product,
)
from sofic.automata.transducers import MealyMachine, MooreMachine, Transducer
from sofic.automata.unifilar import UnifilarAutomaton
from sofic.automata.vpa import (
    CanonicalVisiblyPushdownAutomaton,
    DeterministicVisiblyPushdownAutomaton,
    ModularVisiblyPushdownAutomaton,
    MultipleEntryVisiblyPushdownAutomaton,
    SingleEntryVisiblyPushdownAutomaton,
    VisiblyPushdownAutomaton,
)
from sofic.automata.wheeler import (
    WheelerError,
    WheelerOrder,
    colex_width,
    determinize_wheeler,
    is_input_consistent,
    is_wheeler,
    maximum_colex_relation,
    minimize_wheeler,
    wheeler_canonical_form,
    wheeler_isomorphic,
    wheeler_order,
    wheeler_state_index,
)
from sofic.automata.wheeler_index import WheelerIndex, wheeler_index

__all__ = [
    "Atomaton",
    "AtomicAutomaton",
    "AutomatonEquivalenceOracle",
    "AutomatonLanguage",
    "BuchiAutomaton",
    "EquivalenceOracle",
    "ExhaustiveEquivalenceOracle",
    "FunctionMealyOracle",
    "FunctionMembershipOracle",
    "LanguageMembershipOracle",
    "MealyEquivalenceOracle",
    "MealyExhaustiveEquivalenceOracle",
    "MealyMembershipOracle",
    "MembershipOracle",
    "RandomWalkEquivalenceOracle",
    "TransducerOutputOracle",
    "ModularVisiblyPushdownAutomaton",
    "CanonicalVisiblyPushdownAutomaton",
    "CanonicalRFSA",
    "DFA",
    "DeterministicVisiblyPushdownAutomaton",
    "DyckAlphabet",
    "ERROR_STATE",
    "ERROR_SYMBOL",
    "ICDFAString",
    "LabeledAutomaton",
    "MaximizedPrimeAtomaton",
    "MealyMachine",
    "MinimizationAlgorithm",
    "MooreMachine",
    "MultipleEntryVisiblyPushdownAutomaton",
    "NFA",
    "NestedWord",
    "NestedWordAutomaton",
    "ObservationTable",
    "RegularLanguage",
    "ResidualFiniteStateAutomaton",
    "SingleEntryVisiblyPushdownAutomaton",
    "SubsequentialTransducer",
    "Transducer",
    "UnifilarAutomaton",
    "WeightedFiniteStateTransducer",
    "WheelerError",
    "WheelerIndex",
    "WheelerOrder",
    "VisiblyPushdownAutomaton",
    "automaton_to_regex",
    "colex_width",
    "generator_product",
    "transducer_product",
    "compose_transducer_generator",
    "compose_transducers",
    "complete",
    "count_accessible_idfa",
    "icdfa_count_flag_sequences",
    "count_icdfa",
    "count_icdfa_empty",
    "determinize",
    "dfa_to_icdfa_string",
    "equivalent",
    "first_icdfa_empty_string",
    "first_idfa_string",
    "icdfa_flags_from_string",
    "icdfa_string_to_dfa",
    "is_input_consistent",
    "is_well_matched",
    "is_wheeler",
    "iter_icdfa",
    "iter_icdfa_empty_strings",
    "iter_idfa_strings",
    "last_icdfa_empty_string",
    "MISSING_TRANSITION",
    "learn_dfa_edsm",
    "learn_dfa_from_language",
    "learn_dfa_lstar",
    "learn_dfa_rpni",
    "learn_dfa_sat",
    "learn_dfa_ttt",
    "learn_mealy_from_transducer",
    "learn_mealy_lstar",
    "learn_pfa_alergia",
    "learn_prime_atomaton_nlstar",
    "learn_rfsa_from_language",
    "learn_rfsa_nlstar",
    "learn_sofic_dyck_shift_papni",
    "maximum_colex_relation",
    "minimize",
    "minimize_wheeler",
    "icdfa_next_flags",
    "next_icdfa_empty_string",
    "encode_dyck_word",
    "encode_dyck_samples",
    "rank_idfa_string",
    "reroot_idfa_string",
    "sofic_dyck_shift_from_papni_dfa",
    "icdfa_string_from_flags",
    "trim",
    "transduce_generator",
    "unrank_idfa_string",
    "validate_idfa_string",
    "validate_icdfa_empty_string",
    "wheeler_canonical_form",
    "wheeler_index",
    "wheeler_isomorphic",
    "wheeler_order",
    "wheeler_state_index",
    "determinize_wheeler",
]
