"""Finite automata and transducers."""

# ``atomaton`` is an intentional pun on atomic automaton.
from sofic.automata.active import (
    EquivalenceOracle,
    ExhaustiveEquivalenceOracle,
    FunctionMealyOracle,
    FunctionMembershipOracle,
    LanguageMembershipOracle,
    MealyEquivalenceOracle,
    MealyExhaustiveEquivalenceOracle,
    MealyMembershipOracle,
    MembershipOracle,
    RandomWalkEquivalenceOracle,
    TransducerOutputOracle,
    learn_dfa_from_language,
    learn_dfa_lstar,
    learn_dfa_ttt,
    learn_mealy_from_transducer,
    learn_mealy_lstar,
)
from sofic.automata.alergia import learn_pfa_alergia
from sofic.automata.algorithms import (
    MinimizationAlgorithm,
    complete,
    determinize,
    equivalent,
    minimize,
    trim,
)
from sofic.automata.atomaton import Atomaton, AtomicAutomaton, MaximizedPrimeAtomaton
from sofic.automata.base import LabeledAutomaton
from sofic.automata.buchi import BuchiAutomaton
from sofic.automata.dfa import DFA
from sofic.automata.dfasat import learn_dfa_sat
from sofic.automata.edsm import learn_dfa_edsm
from sofic.automata.icdfa import (
    ICDFAString,
    count_flag_sequences,
    count_icdfa,
    count_icdfa_empty,
    dfa_to_icdfa_string,
    first_icdfa_empty_string,
    flags_from_string,
    icdfa_string_to_dfa,
    iter_icdfa,
    iter_icdfa_empty_strings,
    last_icdfa_empty_string,
    next_flags,
    next_icdfa_empty_string,
    string_from_flags,
    validate_icdfa_empty_string,
)
from sofic.automata.idfa import (
    MISSING_TRANSITION,
    count_accessible_idfa,
    first_idfa_string,
    iter_idfa_strings,
    rank_idfa_string,
    reroot_idfa_string,
    unrank_idfa_string,
    validate_idfa_string,
)
from sofic.automata.languages import AutomatonLanguage, RegularLanguage
from sofic.automata.nfa import NFA
from sofic.automata.nwa import NestedWord, NestedWordAutomaton
from sofic.automata.observation import ObservationTable
from sofic.automata.papni import (
    DyckAlphabet,
    is_well_matched,
    learn_sofic_dyck_shift_papni,
    papni_encode,
    papni_encode_samples,
    sofic_dyck_shift_from_papni_dfa,
)
from sofic.automata.regex import automaton_to_regex
from sofic.automata.rfsa import CanonicalRFSA, ResidualFiniteStateAutomaton
from sofic.automata.rpni import learn_dfa_rpni
from sofic.automata.subsequential import (
    SubsequentialTransducer,
    WeightedFiniteStateTransducer,
)
from sofic.automata.transducer_operations import (
    ERROR_STATE,
    ERROR_SYMBOL,
    cartesian_product_gg,
    cartesian_product_tt,
    compose_tg,
    compose_tt,
    transduce_generator,
)
from sofic.automata.transducers import MealyMachine, MooreMachine, Transducer
from sofic.automata.unifilar import UnifilarAutomaton
from sofic.automata.vpa import (
    CallDrivenAutomaton,
    CanonicalVisiblyPushdownAutomaton,
    CompositeVisiblyPushdownAutomaton,
    DeterministicVisiblyPushdownAutomaton,
    MultipleEntryVisiblyPushdownAutomaton,
    SingleEntryVisiblyPushdownAutomaton,
    VisiblyPushdownAutomaton,
    complement_vpa,
    concat_vpa,
    difference_vpa,
    intersection_vpa,
    kleene_star_vpa,
    union_vpa,
)
from sofic.automata.wheeler import (
    WheelerError,
    WheelerOrder,
    colex_width,
    is_input_consistent,
    is_wheeler,
    maximum_colex_relation,
    minimum_wdfa,
    wheeler_canonical_form,
    wheeler_isomorphic,
    wheeler_order,
    wheeler_state_index,
    wnfa_to_wdfa,
)
from sofic.automata.wheeler_index import WheelerIndex, wheeler_index

__all__ = [
    "Atomaton",
    "AtomicAutomaton",
    "AutomatonLanguage",
    "BuchiAutomaton",
    "EquivalenceOracle",
    "ExhaustiveEquivalenceOracle",
    "FunctionMealyOracle",
    "FunctionMembershipOracle",
    "LanguageMembershipOracle",
    "MealyEquivalenceOracle",
    "MealyExhaustiveEquivalenceOracle",
    "MealyMembershipOracle",
    "MembershipOracle",
    "RandomWalkEquivalenceOracle",
    "TransducerOutputOracle",
    "CallDrivenAutomaton",
    "CanonicalVisiblyPushdownAutomaton",
    "CanonicalRFSA",
    "CompositeVisiblyPushdownAutomaton",
    "DFA",
    "DeterministicVisiblyPushdownAutomaton",
    "DyckAlphabet",
    "ERROR_STATE",
    "ERROR_SYMBOL",
    "ICDFAString",
    "LabeledAutomaton",
    "MaximizedPrimeAtomaton",
    "MealyMachine",
    "MinimizationAlgorithm",
    "MooreMachine",
    "MultipleEntryVisiblyPushdownAutomaton",
    "NFA",
    "NestedWord",
    "NestedWordAutomaton",
    "ObservationTable",
    "RegularLanguage",
    "ResidualFiniteStateAutomaton",
    "SingleEntryVisiblyPushdownAutomaton",
    "SubsequentialTransducer",
    "Transducer",
    "UnifilarAutomaton",
    "WeightedFiniteStateTransducer",
    "WheelerError",
    "WheelerIndex",
    "WheelerOrder",
    "VisiblyPushdownAutomaton",
    "automaton_to_regex",
    "colex_width",
    "cartesian_product_gg",
    "cartesian_product_tt",
    "complement_vpa",
    "compose_tg",
    "compose_tt",
    "concat_vpa",
    "complete",
    "count_accessible_idfa",
    "count_flag_sequences",
    "count_icdfa",
    "count_icdfa_empty",
    "determinize",
    "difference_vpa",
    "dfa_to_icdfa_string",
    "equivalent",
    "first_icdfa_empty_string",
    "first_idfa_string",
    "flags_from_string",
    "icdfa_string_to_dfa",
    "intersection_vpa",
    "is_input_consistent",
    "is_well_matched",
    "is_wheeler",
    "iter_icdfa",
    "iter_icdfa_empty_strings",
    "iter_idfa_strings",
    "last_icdfa_empty_string",
    "MISSING_TRANSITION",
    "kleene_star_vpa",
    "learn_dfa_edsm",
    "learn_dfa_from_language",
    "learn_dfa_lstar",
    "learn_dfa_rpni",
    "learn_dfa_sat",
    "learn_dfa_ttt",
    "learn_mealy_from_transducer",
    "learn_mealy_lstar",
    "learn_pfa_alergia",
    "learn_sofic_dyck_shift_papni",
    "maximum_colex_relation",
    "minimize",
    "minimum_wdfa",
    "next_flags",
    "next_icdfa_empty_string",
    "papni_encode",
    "papni_encode_samples",
    "rank_idfa_string",
    "reroot_idfa_string",
    "sofic_dyck_shift_from_papni_dfa",
    "string_from_flags",
    "trim",
    "transduce_generator",
    "unrank_idfa_string",
    "union_vpa",
    "validate_idfa_string",
    "validate_icdfa_empty_string",
    "wheeler_canonical_form",
    "wheeler_index",
    "wheeler_isomorphic",
    "wheeler_order",
    "wheeler_state_index",
    "wnfa_to_wdfa",
]
