"""
pensive is a Python package for hidden Markov models, symbolic dynamics,
finite state machines, and other stochastic symbol generators.
"""

try:
    from importlib.metadata import version

    __version__ = version("pensive")
except Exception:
    __version__ = "0.0.0"

from pensive.automata import (
    DFA,
    NFA,
    Atomaton,
    AtomicAutomaton,
    AutomatonLanguage,
    BuchiAutomaton,
    CanonicalRFSA,
    LabeledAutomaton,
    MaximizedPrimeAtomaton,
    MealyMachine,
    MinimizationAlgorithm,
    MooreMachine,
    NestedWord,
    NestedWordAutomaton,
    ObservationTable,
    RegularLanguage,
    ResidualFiniteStateAutomaton,
    Transducer,
    UnifilarAutomaton,
    VisiblyPushdownAutomaton,
    automaton_to_regex,
    cartesian_product_gg,
    cartesian_product_tt,
    complete,
    compose_tg,
    compose_tt,
    determinize,
    equivalent,
    minimize,
    transduce_generator,
    trim,
)
from pensive.core import EPSILON, StateIndex, StateMachine, Transition, TransitionGraph
from pensive.generators import (
    BidirectionalEpsilonMachine,
    BlockEntropyDiagram,
    BlockEntropyEstimates,
    BlockConvergenceDiagram,
    BlockConvergenceEstimates,
    EpsilonMachine,
    HiddenMarkovModel,
    HiddenMarkovStackModel,
    MarkovChain,
    MealyHMM,
    MinimalGenerativeModel,
    MixedState,
    MixedStatePresentation,
    MooreHMM,
    NMachine,
    ProbabilisticFiniteAutomaton,
    QuasiRealization,
    QuasiStochasticModel,
    StochasticModel,
    WynerGenerativeModel,
    minimal_generative_model,
    wyner_generative_model,
)
from pensive.operations import reverse
from pensive.serialization import from_yaml, model_from_yaml, model_to_yaml, read_yaml
from pensive.shifts import (
    LeftFischerCover,
    LeftKriegerCover,
    MarkovDyckShift,
    RightFischerCover,
    RightKriegerCover,
    ShiftOfFiniteType,
    SoficDyckShift,
    SoficShift,
    SymbolicModel,
    TopologicalMarkovChain,
)

__all__ = [
    "Atomaton",
    "AtomicAutomaton",
    "AutomatonLanguage",
    "BuchiAutomaton",
    "BidirectionalEpsilonMachine",
    "BlockEntropyDiagram",
    "BlockEntropyEstimates",
    "BlockConvergenceDiagram",
    "BlockConvergenceEstimates",
    "CanonicalRFSA",
    "DFA",
    "EPSILON",
    "EpsilonMachine",
    "HiddenMarkovModel",
    "HiddenMarkovStackModel",
    "LabeledAutomaton",
    "LeftFischerCover",
    "LeftKriegerCover",
    "MarkovDyckShift",
    "MarkovChain",
    "MaximizedPrimeAtomaton",
    "MealyHMM",
    "MinimalGenerativeModel",
    "MealyMachine",
    "MinimizationAlgorithm",
    "MixedState",
    "MixedStatePresentation",
    "MooreHMM",
    "MooreMachine",
    "NFA",
    "NestedWord",
    "NestedWordAutomaton",
    "NMachine",
    "ObservationTable",
    "ProbabilisticFiniteAutomaton",
    "QuasiRealization",
    "QuasiStochasticModel",
    "RegularLanguage",
    "ResidualFiniteStateAutomaton",
    "RightFischerCover",
    "RightKriegerCover",
    "ShiftOfFiniteType",
    "SoficDyckShift",
    "SoficShift",
    "StateIndex",
    "StateMachine",
    "StochasticModel",
    "SymbolicModel",
    "TopologicalMarkovChain",
    "Transducer",
    "Transition",
    "TransitionGraph",
    "UnifilarAutomaton",
    "VisiblyPushdownAutomaton",
    "WynerGenerativeModel",
    "automaton_to_regex",
    "cartesian_product_gg",
    "cartesian_product_tt",
    "complete",
    "compose_tg",
    "compose_tt",
    "determinize",
    "equivalent",
    "minimize",
    "from_yaml",
    "model_from_yaml",
    "model_to_yaml",
    "minimal_generative_model",
    "read_yaml",
    "reverse",
    "transduce_generator",
    "trim",
    "wyner_generative_model",
    "__version__",
]
